export enum ApiActionTypes {
  CREATE_METHOD = "CREATE_METHOD",
  MODIFY_METHOD = "MODIFY_METHOD",
  DELETE_METHOD = "DELETE_METHOD",
  FETCH_METHODS = "FETCH_METHODS",

  CREATE_PHASE = "CREATE_PHASE",
  MODIFY_PHASE = "MODIFY_PHASE",
  DELETE_PHASE = "DELETE_PHASE",
  FETCH_PHASES = "FETCH_PHASES",
}
