export enum ApiMutationTypes {
  SET_CREATE_METHOD = "SET_CREATE_METHOD",
  SET_MODIFY_METHOD = "SET_MODIFY_METHOD",
  SET_DELETE_METHOD = "SET_DELETE_METHOD",
  SET_ALL_METHODS = "SET_ALL_METHODS",

  SET_CREATE_PHASE = "SET_CREATE_PHASE",
  SET_MODIFY_PHASE = "SET_MODIFY_PHASE",
  SET_DELETE_PHASE = "SET_DELETE_PHASE",
  SET_ALL_PHASES = "SET_ALL_PHASES",
}
