export enum ApiMutationTypes {
  SET_CREATE_METHOD = "SET_CREATE_METHOD",
  SET_MODIFY_METHOD = "SET_MODIFY_METHOD",
  SET_DELETE_METHOD = "SET_DELETE_METHOD",
  SET_ALL_METHODS = "SET_ALL_METHODS",
}
