export enum Label {
  METHOD_LABEL_SINGLE = "METHOD_LABEL_SINGLE",
  METHOD_LABEL_PAIR = "METHOD_LABEL_PAIR",
  METHOD_LABEL_GROUP = "METHOD_LABEL_GROUP",
  METHOD_LABEL_PLENUM = "METHOD_LABEL_PLENUM",
}
